Project.MVCUI/Areas/Analyzer/Controllers/AnalyzeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project.BLL.ManagerServices.Abstracts;
using Project.ENTITIES.Models;
using Project.MVCUI.Areas.Creater.CreatorViewModel;

namespace Project.MVCUI.Areas.Analyzer.Controllers
{
    [Area("Analyzer")]
    [Route("[Area]/[Controller]/[Action]")]
    [Authorize(Roles = "Analyzer")]
    public class AnalyzeController : Controller
    {
        private readonly IQuestionManager _questionManager;
        private readonly IMapper _mapper;
        private readonly IGroupManager _groupManager;

        public AnalyzeController(IQuestionManager questionManager, IMapper mapper, IGroupManager groupManager)
        {
            _questionManager = questionManager;
            _mapper = mapper;
            _groupManager = groupManager;
        }

        public async Task<IActionResult> Index()
        {
            IQueryable<Group> groups = await _groupManager.GetGroupsWithQuestions();
            List<Group> result = await groups.ToListAsync();

            List<GroupViewModel> groupViewModels = _mapper.Map<List<GroupViewModel>>(result);
            ViewBag.GroupCodes = result.Select(x => x.Code).ToArray();
            ViewBag.GroupCodeCount = result.Select(x => x.Questions.Count).ToArray();

            return View(groupViewModels);
        }
    }
}

Project.MVCUI/Areas/Creater/Controllers/SurveyController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Project.BLL.ManagerServices.Abstracts;
using Project.ENTITIES.Enums;
using Project.ENTITIES.Models;
using Project.MVCUI.Areas.Creater.CreatorViewModel;
using Project.MVCUI.Extensions;

namespace Project.MVCUI.Areas.Creater.Controllers
{
    [Area("Creater")]
    [Route("[Area]/[Controller]/[Action]")]
    [Authorize(Roles = "Creator")]
    public class SurveyController : Controller
    {
        private readonly ISurveyManager _surveyManager;
        private readonly IAppUserManager _appUserManager;
        private readonly IGroupManager _groupManager;
        private readonly IQuestionManager _questionManager;
        private readonly IMapper _mapper;

        public SurveyController(ISurveyManager surveyManager, IAppUserManager appUserManager, IGroupManager groupManager, IQuestionManager questionManager, IMapper mapper)
        {
            _surveyManager = surveyManager;
            _appUserManager = appUserManager;
            _groupManager = groupManager;
            _questionManager = questionManager;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            List<SurveyViewModel> surveyViewModels = await _surveyManager.GetActives().Select(x => new SurveyViewModel()
            {
                Id = x.Id,
                Name = x.Name
            }).ToListAsync();

            return View(surveyViewModels);
        }

        [HttpGet("{surveyId}")]
        public async Task<IActionResult> SurveyDetail(int surveyId)
        {
            var (error, survey) = await _surveyManager.GetSurveyWithQuestionAndAnswerById(surveyId);

            if (error != null)
            {
                TempData["fail"] = error;
                return RedirectToAction(nameof(Index));
            }

            SurveyViewModel surveyViewModel = _mapper.Map<SurveyViewModel>(survey);

            return View(surveyViewModel);
        }

        public IActionResult AddSurvey()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddSurvey(SurveyViewModel request)
        {
            if (!ModelState.IsValid) return View(request);

            int userId = await _appUserManager.Where(x => x.UserName == User.Identity!.Name).Select(x => x.Id).FirstOrDefaultAsync();

            string? error = await _surveyManager.AddAsync(new()
            {
                Name = request.Name,
                CreatedBy = userId
            });

            if(error != null)
            {
                ModelState.AddModelErrorWithOutKey(error);
                return View(request);
            }

            TempData["success"] = "Anket oluşturuldu";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> UpdateSurvey(int id)
        {
            SurveyViewModel? survey = await _surveyManager.Where(x => x.Id == id && x.Status != DataStatus.Deleted).Select(x => new SurveyViewModel()
            {
                Id = x.Id,
                Name = x.Name,
                CreatedBy = x.CreatedBy
            }).FirstOrDefaultAsync();

            if (survey == null)
            {
                TempData["fail"] = "Anket bulunamadı";
                return RedirectToAction(nameof(Index));
            }

            return View(survey);
        }

        [HttpPost("{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateSurvey(SurveyViewModel request)
        {
            if (!ModelState.IsValid) return View(request);

            string? error = await _surveyManager.UpdateAsync(new()
            {
                Id = request.Id,
                Name = request.Name,
                CreatedBy = request.CreatedBy!.Value
            });

            if(error != null)
            {
                ModelState.AddModelErrorWithOutKey(error);
                return View(request);
            }

            TempData["success"] = "Anket güncellendi";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> DeleteSurvey(int id)
        {
            Survey? survey = await _surveyManager.FindAsync(id);
            if(survey == null)
            {
                TempData["fail"] = "Anket bulunamadı";
                return RedirectToAction(nameof(Index));
            }

            string? error = await _surveyManager.DeleteAsync(survey);
            if(error != null)
            {
                TempData["fail"] = error;
                return RedirectToAction(nameof(Index));
            }

            TempData["success"] = "Anket silindi";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet("{surveyId}")]
        public async Task<IActionResult> AddQuestionToSurvey(int surveyId)
        {
            List<GroupViewModel> groupViewModels = await _groupManager.GetActives().Select(x => new GroupViewModel()
            {
                Id = x.Id,
                Code = x.Code,
                Score = x.Score
            }).ToListAsync();

            TempData["groupSelectList"] = new SelectList(groupViewModels, nameof(GroupViewModel.Id), nameof(GroupViewModel.Code));

            QuestionViewModel questionViewModel = new QuestionViewModel() { SurveyId = surveyId };

            return View(model: questionViewModel);
        }

        [HttpPost("{surveyId}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddQuestionToSurvey(QuestionViewModel request)
        {
            Question question = _mapper.Map<Question>(request);
            question.ChildQuestions = null;

            string? result = await _questionManager.AddAsync(question);
            if (result != null)
            {
                TempData["fail"] = result;
                return RedirectToAction(nameof(Index));
            }

            if(request.ChildQuestions != null && request.ChildQuestions.Count > 0)
            {
                question.ChildQuestions = _mapper.Map<List<Question>>(request.ChildQuestions);

                string? result2 = await _questionManager.AddRangeAsync(question.ChildQuestions);
                if (result2 != null)
                {
                    TempData["fail"] = result2;
                    return RedirectToAction(nameof(Index));
                }
            }          

            TempData["success"] = "Anket sorusu eklendi";
            return RedirectToAction(nameof(Index));
        }
    }
}

Project.MVCUI/Views/Shared/_AlertFailPartial.cshtml
@model string

<div class="alert alert-danger d-flex align-items-center alert-dismissible fade show" role="alert">

    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
    </svg>

    <span class="ms-2">@Model</span>

    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>

</div>

Project.MVCUI/Views/Shared/_AlertSuccessPartial.cshtml
@model string

<div class="alert alert-success d-flex align-items-center alert-dismissible fade show" role="alert">

    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
    </svg>

    <span class="ms-2">@Model</span>

    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>

</div>

Project.MVCUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agency</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project.MVCUI.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Css", required: false)
</head>
<body>

    @{
        bool isAuthenticated = User.Identity!.IsAuthenticated;
        bool isCreator = User.IsInRole("Creator");
        bool isResponder = User.IsInRole("Responder");
        bool isAnalyzer = User.IsInRole("Analyzer");
    }

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="/Home">Agency</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 d-flex justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Home">Ana Sayfa</a>
                        </li>
                        @if (isCreator)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Creater" asp-controller="Survey" asp-action="Index">Anketler</a>
                            </li>
                        }
                        else if (isResponder)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Responder" asp-controller="Survey" asp-action="Index">Anketler</a>
                            </li>
                        }
                        else if (isAnalyzer)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Analyzer" asp-controller="Analyze" asp-action="Index">Analiz</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav align-items-center">
                        @if (!isAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="btn btn-outline-success" style="border-radius:20px;" asp-area="" asp-controller="Home" asp-action="Login">Giriş Yap</a>
                            </li>
                        }
                        else
                        {
                            <li class="dropdown">
                                <button class="rounded rounded-pill" style="background-color:white;" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z" />
                                    </svg>
                                </button>
                                <ul class="dropdown-menu" style="border-radius:20px;" aria-labelledby="dropdownMenu2">
                                    @if(isCreator){
                                        <li><a class="dropdown-item" asp-area="Creater" asp-controller="Survey" asp-action="Index">Anketler</a></li>
                                    }
                                    else if (isResponder)
                                    {
                                        <li><a class="dropdown-item" asp-area="Responder" asp-controller="Survey" asp-action="Index">Anketler</a></li>
                                    }
                                    else if (isAnalyzer)
                                    {
                                        <li><a class="dropdown-item" asp-area="Analyzer" asp-controller="Analyze" asp-action="Index">Analiz</a></li>
                                    }

                                    <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Logout" asp-route-returnUrl="/Home">Çıkış Yap</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Agency Project
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>